### ISSUE TITLE
Is the maintainer deceased?

### ISSUE THREAD

**Issue by thinkyhead** [batari-Basic/batari-Basic#11]
It appears that the maintainer of this project organization may be deceased, kidnapped, or in a coma. If this is the case please let us know so that we can move this project to a new repository and assign it to a living, breathing maintainer. Thank you for any information and assistance you can provide.

**Comment by msaarna** [comment]
Not deceased, I'm just pining for the fjords. There was a release put out only two months ago.

There is a backlog of PRs. Due to the review time required for review, and after shooting myself in the foot a couple years back by accepting a large formatting/cleanup PR that broke bB rather badly in unexpected and subtle ways, I'm not entertaining PRs at the moment. That may change, but probably not soon.
 
Of course, forking is always an option.

**Comment by thinkyhead** [comment]
> shooting myself in the foot

The newer PRs are intentionally more simplified and targeted to avoid that pitfall.

**Comment by thinkyhead** [comment]
> Of course, forking is always an option.

Everyone who wants to contribute is required to fork. Whether the project "forks" is a matter of whether it is actively managed or not. If PRs are not going to be reviewed in a timely manner so that more PRs can follow, the project is effectively dead.
