### ISSUE TITLE
Either update or take down bataribasic.com

### ISSUE THREAD

**Issue by darkhog** [batari-Basic/batari-Basic#14]
It's the first result in google and due to it being very outdated, may confuse newcomers that just want to try it. Not sure if any of the current devs have access to that site (though somebody obviously must be paying for hosting/domain name), but yeah, having it around in the state it currently is (with last post related to 1.0, when we are already on 1.7 and then some BS about crediting your car or whatever) is really confusing for anyone who heard about Batari as an easy way to make 2600 games and wants to try that.

**Comment by msaarna** [comment]
Agreed that it's not great, but nobody associated with batari Basic actually owns the domain. 

The domain was originally owned by Fred Quimby, who created batari Basic. But the domain lapsed a number of years ago, and someone took over the domain and setup that copycat site, presumably to keep the search rank and serve out spam ads. (scroll down the page to see them)

I'm closing the issue, because there's nothing we can do.
