### ISSUE TITLE
64kSC explicits

### ISSUE THREAD

**Issue by The-Major-Havoc** [batari-Basic/batari-Basic#16]
Hello gentlemen  :)
My project compiles but shows only a black screen when changing from 32k to 64k.

 I scoured the forums and found some nuances :
    you must explicitly use "gosub label bank#" with "return otherbank".
    you must explicitly use "gosub label" with "return" or "return thisbank". (under 64k, "return" is the same as "return thisbank")
 However, this would require some serious re-writing of my sourcecode.
  
I was wondering if this issue still being worked on.

**Comment by msaarna** [comment]
It's a limitation, and there's no plan to address it presently. bB uses the unused address space on the 6507 to represent a bank+return address without extra bloat. Unfortunately there are only 3 bits of storage available in the unused address space, so that's not good enough for the 16 banks in the 64K format.

Any implicit bankswitch kludge would bloat your existing project and cause similar rework. The reason for using a big format like 64K is a need for rom, so with a new project, squandering the rom space just to enable implicit bankswitching isn't a worthwhile trade-off.

I've updated the ISSUES.TXT document to explicitly call it out.

**Comment by The-Major-Havoc** [comment]
Thanks Mike!
 One more question.
Does a Vblank subroutine need to be addressed with "return" or "return otherbank" when using 64KSC?

**Comment by msaarna** [comment]
You're welcome!
Vblank is should be returned with "return thisbank" (and yes, just plan "return" is equivalent to that when using a 64K rom)
